name: Backend CI/CD

on:
  push:
    branches:
      - main
      - dev
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Get code from GitHub
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Install Java 21
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # 3️⃣ Build JAR (this creates build/libs/*.jar)
      - name: Build backend
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test

      # 4️⃣ Build Docker image (uses your Dockerfile)
      - name: Build Docker image
        run: docker build -t askverse-backend .

      # 5️⃣ Save image to file
      - name: Save Docker image
        run: docker save askverse-backend > askverse-backend.tar

      # 6️⃣ Copy image to server
      - name: Copy image to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "quora-backend.tar"
          target: "/home/ubuntu"

      # 7️⃣ Run container on server
      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker load < quora-backend.tar
            docker stop quora-backend || true
            docker rm quora-backend || true
            docker run -d \
              --name quora-backend \
              -p 8080:8080 \
              quora-backend
  